### ISSUE TITLE
Add propper web.config section (IIS) for handling Angular2 routing

### ISSUE THREAD

**Issue by Carl012** [Drag13/MvcWithAngular2#1]
Hi,

In order to support angular routing, it could be a good idea to add something like this to the Web.config:

```
<system.webServer>
    <rewrite>
      <rules>
        <rule name="AngularJS Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
            <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
```

I hope it will save some people the time I lost figuring this out.
Thanks!

**Comment by Drag13** [comment]
Great idea. Thank you for investigation!

**Comment by Drag13** [comment]
Your codes works fine.
I will add routing, checkin changes in a few days and close this issue.
Template will be updated next week.

Thanks once more for your help and come back with new idea )

P.S. You can find your name in TyList.html.

**Comment by Karuppusamyt** [comment]
Thanks This work fine!
