### ISSUE TITLE
How do I add Angular itself to this project?

### ISSUE THREAD

**Issue by wcdeich4** [Drag13/MvcWithAngular2#3]
Hi. I just created a Angular2WebTemplate project & tried to display it & got the error "Error	TS2307	Cannot find module '@angular/core'."

So, how do I put the Angular files into this template?

**Comment by Drag13** [comment]
Hi @wcdeich4 ,
Angular 2 already there. Please, check your node_modules folder to be sure you have installed it. 
Also please check your npm and node version running npm -v  and node -v from taskrunner. 
More information about potential problems you can find in readme.

**Comment by wcdeich4** [comment]
Hi.  I installed NodeJS & restarted Visual Studio, but when I recompile, I still get "Error	TS2307	Cannot find module '@angular/core'."  Maybe I'm being really dumb here....

**Comment by Drag13** [comment]
Please open your project folder and find node_modules folder. Do you see there angular folder?

**Comment by Drag13** [comment]
You need to check next point.
1. Be sure you install angulat app. (check angular folder)
2. Be sure you install it without error. (check task runner log)
If all is ok, come back and we will think what next)

**Comment by Drag13** [comment]
@wcdeich4 Let me know if your problem is solved. I wont to close this issue on Friday if no answer.

**Comment by wcdeich4** [comment]
Sorry I got distracted w/ other work.  There is no node_modules folder inside the Angular2WebTemplate1 project created.  I tried chaning the npm path in the system.config.js to 'C:/Program Files/nodejs/node_modules' but still get the same error

**Comment by Drag13** [comment]
This mean that you do not installed angular.
Please go [here](https://github.com/Drag13/MvcWithAngular2) and read how to install angular and all dependencies. Here you can find simple step by step  manual. Please, follow it and all should be ok.

**Comment by wcdeich4** [comment]
C:\Users\v-wdeich\documents\visual studio 2015\Projects\Angular2WebTemplate1\Angular2WebTemplate1> cmd.exe /c npm install --color=always
> myproject@1.4.2 postinstall C:\Users\v-wdeich\documents\visual studio 2015\Projects\Angular2WebTemplate1\Angular2WebTemplate1
> typings install
typings WARN enoent Path "C:\Users\v-wdeich\documents\visual studio 2015\Projects\Angular2WebTemplate1\Angular2WebTemplate1\typings.json" is missing
└── (No dependencies)
npm WARN EPEERINVALID @angular/core@2.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN EPEERINVALID @angular/http@2.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN EPEERINVALID @angular/router@3.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN EPEERINVALID angular2-in-memory-web-api@0.0.21 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
Process terminated with code 0.

**Comment by Drag13** [comment]
Sry was a bit busy. So, code 0 means that installation completed successfully. Problem still exists? Does angular2 presented in node_modules folder?

**Comment by wcdeich4** [comment]
Oh.  Strange. It looked like a error message in Visual Studio. I was just experimenting w/ MvcWithAngular2 template - I'll have to see if I find time to experiment more later.
