### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by madibi** [Drag13/MvcWithAngular2#4]
this extension is not install-able on any currently installed production!

i am using visual studio 2017

**Comment by Drag13** [comment]
If you are speaking about [this ](https://marketplace.visualstudio.com/items?itemName=Drag13.Angular2WebTemplate) extension than it is not for VS17. It is for VS15 only.
If you cloned this repo and try to install all from the 0 - check that you have propper NPM and Node. Usually they cause main problems. 

In any case,  I can't hlep you without details.
